### ISSUE TITLE
Which is generally the highest quality?

### ISSUE THREAD

**Issue by Sawtaytoes** [the-database/AnimeJaNaiConverterGui#7]
I ran `UltraCompact` and `Compact` on the same video and both Compact and UltraCompact look the same. It's hard for me to tell a difference as I don't know where to look. The `UltraCompact` one is slightly larger in filesize though.

Not sure about `SuperUltraCompact`. It has 100k in the name which means 100k iterations? Wouldn't that mean it's higher quality?

Also, do the different versions have a different speed? On my NVIDIA RTX 3090, they all seem to run at roughly the same speed.

I'm really new to this.

**Comment by the-database** [comment]
In order of highest quality and slowest to run: Compact, UltraCompact, SuperUltraCompact. 100k does refer to iterations but that doesn't say anything about quality relative to other models. 

They do have different speeds, benchmarks are available here: https://github.com/the-database/mpv-upscale-2x_animejanai/wiki/Benchmarks

However, the benchmarks above measure the upscaling step only. When you run the converter GUI, you are upscaling and encoding to a video file at the same time. It's common for the encoding to be the bottleneck, so that would explain why you can see the same speed on different models. The NVENC hardware encoder is a good option to speed up encoding.

**Comment by Sawtaytoes** [comment]
Thanks for your information!

This is exactly what I was looking for and explains why performance was relatively similar; even slower for the SuperUltraCompact run (because I had other network tasks going at the same time).

I should use my NVMe drives rather than targeting files directly over SMB to my NAS. Even with a 25Gb connection, there's gonna be more lag in the transfer than when going directly to my NAS, and it sounds like I could greatly speed this up by having them on disk!
